name: Doplone
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-sitemap
baseurl: /doplone
url: http://dhanyacm.github.io/
include: ["_pages"]
collections:
- poetry
- collectables
- events
collections_dir: my_collections
permalink: /:title/

