name: Doplone
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-sitemap
baseurl: /doplone
url: http://dhanyacm.github.io/
collections:
- poetry
- collectables
- events
collections_dir: my_collections
